dist: xenial
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"
    - os: linux
      addons:
        apt:
          sources:
            - llvm-toolchain-xenial-8
          packages:
            - clang-8
      env:
        - MATRIX_EVAL="CC=clang-8 && CXX=clang++-8"

#    - os: osx
#      osx_image: xcode10.1
#      env:
#        - MATRIX_EVAL="PATH=$HOME/Library/Python/2.7/bin:$PATH && CC=clang && CXX=clang++"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - pyenv global 3.7.1
  - pip install --upgrade pip
  - pip install cmake ninja conan pytest

script:
  - conan install -if build -g cmake_paths --build=missing .
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -Bbuild -DENABLE_UNITTESTS_IN_BUILD=OFF -DCMAKE_PROJECT_INCLUDE=build/conan_paths.cmake .
  - cmake --build build --target check-unit
  - cmake --build build --target check-functional
