dist: xenial
sudo: required
language: cpp

matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-9
            - g++-9
      env:
        - MATRIX_EVAL="CC=gcc-9 && CXX=g++-9"

    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="PATH=$HOME/Library/Python/2.7/bin:$PATH && CC=clang && CXX=clang++"

before_install:
    - eval "${MATRIX_EVAL}"

install:
  - pip install --user -U pip
  - pip install --user cmake ninja conan pytest

script:
  - conan install -if build . --build=missing
  - cmake -GNinja -DCMAKE_BUILD_TYPE=Release -Bbuild -DCMAKE_PROJECT_SemVer_INCLUDE=$(pwd)/build/conan_paths.cmake .
  - cmake --build build
  - cmake --build build --target test