name: CI

on: [push]

jobs:
  analyse:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout worktree
        uses: actions/checkout@v3
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install cmake ninja conan pytest
      - name: Install dependencies
        run: |
          ls -la
          conan install -if build -g cmake_paths --build=missing .
      - name: Configure
        run: |
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -Bbuild -DENABLE_UNITTESTS_IN_BUILD=OFF -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DENABLE_TIDY=ON -DCMAKE_PROJECT_SemVer_INCLUDE=build/conan_paths.cmake .
      - name: Run clang-tidy
        run: |
          cmake --build build --target tidy


  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout worktree
        uses: actions/checkout@v3
      - name: Set up GCC
        uses: egor-tensin/setup-gcc@v1
        with:
          version: latest
          platform: x64
      - name: Install tools
        run: |
          pip install --upgrade pip
          pip install cmake ninja conan pytest
      - name: Install dependencies
        run: |
          ls -la
          conan install -if build -g cmake_paths --build=missing .
      - name: Configure
        run: |
          cmake -GNinja -DCMAKE_BUILD_TYPE=Release -Bbuild -DENABLE_UNITTESTS_IN_BUILD=OFF -DCMAKE_PROJECT_SemVer_INCLUDE=build/conan_paths.cmake .
      - name: Run unit tests
        run: |
          cmake --build build --target check-unit
      - name: Run functional tests
        run: |
          cmake --build build --target check-functional
